name: cldla_0.1.1
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
dependencies:
  - bioconda::pysam=0.20.0
  - pyyaml=6.0.1
  - numpy=1.26.0
  - scipy=1.11.3
  - pip:
      - pyqt5-sip==12.11.0
